#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Alias for "ddev silo" (launch a browser with Silo console)
## Usage: minio
## Example: "ddev minio"

ddev silo "$@"
