#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Silo console
## Usage: silo
## Example: "ddev silo"

echo "Login using 'ddevminio' user and 'ddevminio' password (or 'ddevsilo' / 'ddevsilo')"

DDEV_SILOCONSOLE_PORT=9089
DDEV_SILOCONSOLE_HTTPS_PORT=9090

if [ ${DDEV_PRIMARY_URL%://*} = "http" ] || [ -n "${GITPOD_WORKSPACE_ID:-}" ] || [ "${CODESPACES:-}" = "true" ]; then
    ddev launch :$DDEV_SILOCONSOLE_PORT
else
    ddev launch :$DDEV_SILOCONSOLE_HTTPS_PORT
fi
